name: Build Android
on:
  push:
    branches: [master]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install NPM dependencies
        run: yarn install
        
      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew
        
      - name: Build Android App Bundle
        run: |
          cd android && ./gradlew bundleRelease --no-daemon
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: appRelease
          path: android/app/build/outputs/bundle/release/app.aab
